import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";

export default defineConfig({
  extends: [core, react, tanstack],
  ignorePatterns: [...(core.ignorePatterns ?? []), "src/wasm/**"],
  overrides: [
    {
      files: ["scripts/**"],
      rules: {
        "no-console": "off",
      },
    },
  ],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  // The compatibility overrides intentionally follow the existing project style.
  rules: {
    complexity: "warn",
    "func-style": "off",
    "react/function-component-definition": "off",
    "unicorn/filename-case": "off",
    "unicorn/throw-new-error": "off",
    curly: "off",
    "no-console": ["warn", { allow: ["error", "warn"] }],
    "no-else-return": "off",
    "typescript/await-thenable": "error",
    "typescript/consistent-return": "warn",
    "typescript/consistent-type-exports": "off",
    "typescript/dot-notation": "off",
    "typescript/no-array-delete": "off",
    "typescript/no-base-to-string": "off",
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-deprecated": "off",
    "typescript/no-duplicate-type-constituents": "off",
    "typescript/no-floating-promises": "off",
    "typescript/no-for-in-array": "off",
    "typescript/no-implied-eval": "error",
    "typescript/no-meaningless-void-operator": "off",
    "typescript/no-misused-promises": "warn",
    "typescript/no-misused-spread": "off",
    "typescript/no-mixed-enums": "off",
    "typescript/no-redundant-type-constituents": "off",
    "typescript/no-unnecessary-boolean-literal-compare": "off",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-qualifier": "off",
    "typescript/no-unnecessary-template-expression": "off",
    "typescript/no-unnecessary-type-arguments": "off",
    "typescript/no-unnecessary-type-assertion": "off",
    "typescript/no-unnecessary-type-conversion": "off",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-argument": "off",
    "typescript/no-unsafe-assignment": "off",
    "typescript/no-unsafe-call": "error",
    "typescript/no-unsafe-enum-comparison": "off",
    "typescript/no-unsafe-member-access": "error",
    "typescript/no-unsafe-return": "error",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-unsafe-unary-minus": "off",
    "typescript/no-useless-default-assignment": "off",
    "typescript/non-nullable-type-assertion-style": "off",
    "typescript/only-throw-error": "off",
    "typescript/prefer-find": "off",
    "typescript/prefer-includes": "off",
    "typescript/prefer-nullish-coalescing": "off",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-promise-reject-errors": "off",
    "typescript/prefer-readonly": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "off",
    "typescript/prefer-regexp-exec": "off",
    "typescript/prefer-return-this-type": "off",
    "typescript/prefer-string-starts-ends-with": "off",
    "typescript/promise-function-async": "off",
    "typescript/related-getter-setter-pairs": "off",
    "typescript/require-array-sort-compare": "off",
    "typescript/require-await": "off",
    "typescript/restrict-plus-operands": "off",
    "typescript/restrict-template-expressions": "off",
    "typescript/return-await": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "typescript/switch-exhaustiveness-check": "off",
    "typescript/unbound-method": "off",
    "typescript/use-unknown-in-catch-callback-variable": "off",
    "unicorn/prefer-ternary": "off",
  },
});
