export const PALETTE_COLORS = [
  { hex: "#000000", name: "black" },
  { hex: "#808080", name: "grey" },
  { hex: "#ffffff", name: "white" },
  { hex: "#e53935", name: "red" },
  { hex: "#ff8a80", name: "light-red" },
  { hex: "#ff8a65", name: "orange" },
  { hex: "#ffd54f", name: "yellow" },
  { hex: "#81c784", name: "light-green" },
  { hex: "#4caf50", name: "green" },
  { hex: "#8ab4ff", name: "light-blue" },
  { hex: "#3d7eff", name: "blue" },
  { hex: "#7c4dff", name: "violet" },
  { hex: "#c8bfff", name: "light-violet" },
  { hex: "#f06292", name: "pink" },
  { hex: "#26a69a", name: "teal" },
];
