/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as LobbyRouteRouteImport } from './routes/lobby/route'
import { Route as MenuRouteRouteImport } from './routes/menu/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as LobbyIndexRouteImport } from './routes/lobby/index'
import { Route as LobbyIdRouteImport } from './routes/lobby/$id'
import { Route as MenuIndexRouteImport } from './routes/menu/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRouteRoute = LobbyRouteRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRouteRoute = MenuRouteRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LobbyIndexRoute = LobbyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LobbyRouteRoute,
} as any)
const LobbyIdRoute = LobbyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LobbyRouteRoute,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/lobby': typeof LobbyRouteRouteWithChildren
  '/menu': typeof MenuRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/auth/': typeof AuthIndexRoute
  '/lobby/': typeof LobbyIndexRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/auth': typeof AuthIndexRoute
  '/lobby': typeof LobbyIndexRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/lobby': typeof LobbyRouteRouteWithChildren
  '/menu': typeof MenuRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/lobby/$id': typeof LobbyIdRoute
  '/auth/': typeof AuthIndexRoute
  '/lobby/': typeof LobbyIndexRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lobby'
    | '/menu'
    | '/error'
    | '/lobby/$id'
    | '/auth/'
    | '/lobby/'
    | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/error' | '/lobby/$id' | '/auth' | '/lobby' | '/menu'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/lobby'
    | '/menu'
    | '/error'
    | '/lobby/$id'
    | '/auth/'
    | '/lobby/'
    | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LobbyRouteRoute: typeof LobbyRouteRouteWithChildren
  MenuRouteRoute: typeof MenuRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/lobby/': {
      id: '/lobby/'
      path: '/'
      fullPath: '/lobby/'
      preLoaderRoute: typeof LobbyIndexRouteImport
      parentRoute: typeof LobbyRouteRoute
    }
    '/lobby/$id': {
      id: '/lobby/$id'
      path: '/$id'
      fullPath: '/lobby/$id'
      preLoaderRoute: typeof LobbyIdRouteImport
      parentRoute: typeof LobbyRouteRoute
    }
    '/menu/': {
      id: '/menu/'
      path: '/'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface LobbyRouteRouteChildren {
  LobbyIdRoute: typeof LobbyIdRoute
  LobbyIndexRoute: typeof LobbyIndexRoute
}

const LobbyRouteRouteChildren: LobbyRouteRouteChildren = {
  LobbyIdRoute: LobbyIdRoute,
  LobbyIndexRoute: LobbyIndexRoute,
}

const LobbyRouteRouteWithChildren = LobbyRouteRoute._addFileChildren(
  LobbyRouteRouteChildren,
)

interface MenuRouteRouteChildren {
  MenuIndexRoute: typeof MenuIndexRoute
}

const MenuRouteRouteChildren: MenuRouteRouteChildren = {
  MenuIndexRoute: MenuIndexRoute,
}

const MenuRouteRouteWithChildren = MenuRouteRoute._addFileChildren(
  MenuRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LobbyRouteRoute: LobbyRouteRouteWithChildren,
  MenuRouteRoute: MenuRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
